### ISSUE TITLE
DOCUMENT_TEXT_DETECTION vs TEXT_DETECTION

### ISSUE THREAD

**Issue by Meerkov** [SethRobinson/UGT#24] opened 2021-04-23 20:39 UTC
From what I've read, TEXT_DETECTION is more robust, but DOCUMENT_TEXT_DETECTION is intended for documents.

My hunch is that games are probably closer to Document scans than generic photos of street signs. They are already flat, well oriented, with text that isn't skewed or effected by lighting...

I made a quick experiment to test the difference.

Here is TEXT_DETECTION
![Screenshot_00048](https://user-images.githubusercontent.com/8139496/115927135-cb3f9e00-a438-11eb-8188-4816888d1bbf.jpg)

Here is DOCUMENT_TEXT_DETECTION
![Screenshot_00049](https://user-images.githubusercontent.com/8139496/115927162-d85c8d00-a438-11eb-91ec-027ec83e4413.jpg)

Notice especially the first line, where he's telling us this is his first vacation in a long time.
"It was a physical leisure battle for the first time in a long time."
vs
"It's been a while since I was free."

The second translation is *much* more natural (though still not perfect). The only problem with the change, is that I think the output format is different than expected. The first line of text is repeated twice, indicating the problem.

I think it would be good to look into changing the API call, and making the associated changes, as it improves the translation dramatically.

**Comment by Meerkov** [comment] 2021-04-23 23:47
Note this is more of a "more research is needed" issue. I'm not sure which would be better for the common case, as this is only one screenshot from one game. But it's worth looking into I think.

**Comment by SethRobinson** [comment] 2021-04-24 04:35
Wow, that's a big difference in translation, had no idea! 

I'm thinking maybe enabling DOCUMENT_TEXT_DETECTION for anything it thinks is "dialog" (green text) might be a good option.   I'll do some tests, maybe add a config.txt setting for "always", "never", "dialog only" or something.

**Comment by Meerkov** [comment] 2021-04-24 07:24
Well, the option is for the Vision API, not the translation API. It is intended to tell the API that you're looking for text in something that is "document like", such as a PDF, a receipt, a scan of an invoice, etc. I figured any sort of computer text probably falls into this category.

The idea is that the vision API gets a hint that the words are essentially on a flat piece of paper, not skewed by perspective, or at random angles unrelated to each other. Better vision yields more accurate character OCR. Then those characters are fed into the translation, resulting in the more accurate translation.

**Comment by SethRobinson** [comment] 2021-04-25 11:04
Ah, understood.  Sounds like a good change though, will play with it.

**Comment by SethRobinson** [comment] 2021-05-19 19:21
Added as config.txt option and is now the default - 7157daf

**Comment by SethRobinson** [comment] 2021-05-20 11:14
Ok, after playing with it with a real game I noticed a downside - it tends to group text that isn't near each other into one block, I'll have to leave TEXT_DETECTION  as the default but it can be easily enabled with the new config.txt option.  
![bug3](https://user-images.githubusercontent.com/394547/118969325-e48c2980-b9a7-11eb-997b-4bad939066bb.png)

As a test case, all the text on this image usually gets put into a single text block when DOCUMENT_TEXT_DETECTION is active.  Weird.

**Comment by Meerkov** [comment] 2021-07-20 04:32
Please try again with the text duplication bug fix in https://github.com/SethRobinson/UGT/issues/33

It's possible what you're seeing is actually that bug, and nothing to do with DOCUMENT_TEXT_DETECTION.

**Comment by SethRobinson** [comment] 2021-07-20 10:26
Hmm, same results, it tends to put things in a single large text block.  (not always but mostly it kind of depends on the exact capture size)

Here is with DOCUMENT_TEXT_DETECTION:

![text_detect1](https://user-images.githubusercontent.com/394547/126308429-e4eda572-2e60-4587-89e4-4612a2fb9eba.png)

For comparison, here is with TEXT_DETECTION set, Google decides to separate them:

![text_detect2](https://user-images.githubusercontent.com/394547/126308561-a2d9a3a3-9006-4272-9ca2-f0c21eb60f39.png)

**Comment by Meerkov** [comment] 2021-07-20 15:45
I've been using DOCUMENT_TEXT_DETECTION for a while, and I haven't noticed this happening too often. Maybe it's my workflow.

I usually translate the entire window, but it looks like you try to tightly fit your translation box to only the text. What happens if you translate the whole window/image? Maybe that will change the result.

Also note that the resolution you translate at likely effects the results. Your code specifically merges text boxes that are within a certain number of pixels of each other. So what you are seeing could be related to that merge code, rather than the API... I'm not sure.

**Comment by SethRobinson** [comment] 2021-07-21 10:53
You could be right that DOCUMENT_TEXT_DETECTION is better overall, I was actually having problems with translating a normal webpage because 
Google was cutting up each line (it had somewhat fat vertical spacing between lines) instead of doing it as a whole paragraph.  It appears using DOCUMENT_TEXT_DETECTION fixes that, as it relaxes the "cutting it up into chunks" algorithm they use.

Also, by accident the default mode was actually set to DOCUMENT_TEXT_DETECTION in the last few versions, so I guess I'll leave it for now, as I keep testing with it.

**Comment by jotumn** [comment] 2021-07-31 19:24
I've been checking it out and perhaps you could implement an option of overriding Google's OCR results? There's a game I'm playing which tends to split text due to low resolution:
![image](https://user-images.githubusercontent.com/16961866/127750324-b826659b-bc85-4e32-9171-cf8ddb4688e7.png)

The problem is that document mode splits that into separate strings (which is incorrect) unless I manually select the smallest possible area. Which tends to be a hassle because I have to do it for maybe 70% of lines (in 30% of cases Google makes it a continuous block of text by itself). Text mode is significantly worse and often just can't OCR words at all. So the solution would be to use document mode, then join the strings on the client side and then send the resulting string for translation. That's not applicable in cases when the UI is present, of course, but for most of VNs I'm guessing this would be perfect except for the ones that put the character name on top. And that can be remedied by the selection area.

**Comment by SethRobinson** [comment] 2021-08-01 01:42
Hrm, have you tried the latest (V0.70) release?  It does do a much better job of removing linefeeds and sending it as one string.  Here is what it looks like for me (with document mode): 

Using Google to  translate:

![ugt_textgoogle](https://user-images.githubusercontent.com/394547/127756501-10ca1aae-e8b6-493f-81ae-f1f2c7128a14.png)

Using DeepL:

![ugt_text](https://user-images.githubusercontent.com/394547/127756409-a04ade31-2dd0-4687-b477-6e6455950a34.png)

In the last release I did write some code that connects text blocks into one big one if it looks like it should.

**Comment by jotumn** [comment] 2021-08-01 09:58
I'm using 0.70. Sorry, I've picked a random screenshot to illustrate another point. Let me find something that doesn't work right... This one:
![image](https://user-images.githubusercontent.com/16961866/127766751-e53df928-9a54-4315-b14c-2d8df01fdf10.png)

If I select the big area:
![image](https://user-images.githubusercontent.com/16961866/127766766-2a015588-ebc1-4400-aad2-972607bb391a.png)

Whole screen:
![image](https://user-images.githubusercontent.com/16961866/127766777-09f05c9e-5192-4d9a-9e72-87a9b1c556c9.png)

Custom small area (text is glued together by Google properly like I want it to):
![image](https://user-images.githubusercontent.com/16961866/127766797-670a23f0-0abe-47cd-aa25-8024519c3a68.png)

It's all DeepL and document mode.

TEXT_DETECTION just doesn't find anything at all:
![image](https://user-images.githubusercontent.com/16961866/127766847-0025364c-a828-4e4f-a444-12320026e716.png)
![image](https://user-images.githubusercontent.com/16961866/127766855-afef2a21-1199-48e9-8bbe-e0028105b6c3.png)
![image](https://user-images.githubusercontent.com/16961866/127766864-f07a5aaf-af3b-4dab-af28-62be73385136.png)

**Comment by jotumn** [comment] 2021-08-01 10:02
> In the last release I did write some code that connects text blocks into one big one if it looks like it should.

I think that a simple auto-glue config flag would just solve all this, for me at least. I tend to select small areas in game window to both speed up the sending process and it just works better (Google finds 320x240 pixellated text way better in smaller areas as I've found out). While it looks like you prefer to use the whole screen, probably because it eliminates the hassle of selecting area manually.

**Comment by Meerkov** [comment] 2021-08-01 21:19
So, I don't want this thread to get too off-topic. This thread was really about DOCUMENT_TEXT_DETECTION vs TEXT_DETECTION. It seems like from the screenshots you're showing, DOCUMENT_TEXT_DETECTION is still superior, so I think we can probably close this thread and mark this fixed, since I think everyone is happier with DOCUMENT mode so far, and if they are not, there is now a configuration option.

The questions about how to merge text boxes I think are valid, but I'd probably recommend opening a new thread so those concerns don't get lost.

**Comment by SethRobinson** [comment] 2021-08-01 22:33
Ok, one thing before I forget though - I noticed when testing on jotumn's screenshots is the current "auto-glue" did seem to work (even when scanning the whole page), but <sometimes> it decided to use line-by-line mode for the translation. (white color, not green)

jotumn, if you click the text box, you'll see a square around it, does the square show it's actually one block and not two and auto-glue is working?  If so, press D to force dialog mode and it will probably fix the translation.  (albeit, only until the next scan)

So what we may actually need is a "force everything to be dialog" all the time option/slider, hrm.  It's just guessing right now based on things like if it finds punctuation or not. For people who aren't translating menu options, they probably don't want line-by-line translations at all.

**Comment by jotumn** [comment] 2021-08-02 11:39
Pressing D indeed fixes this (it says "forcing dialog translation mode" for a second):
![image](https://user-images.githubusercontent.com/16961866/127855690-984b12e7-8a1e-4576-9af9-9b8c58f514fa.png)

If only I knew about this shortcut before! Then I wouldn't have to do it manually every time for the past 2 or 3 hours of gameplay that was left :D

> So what we may actually need is a "force everything to be dialog" all the time option/slider, hrm. 

You can instead change the D shortcut to toggle, setting mode until D is pressed again. That won't require another config option.

**Comment by SethRobinson** [comment] 2021-08-03 00:17
Good idea.  Ok, I'm going to add this soon, will be a good test to see if the "notify on new update" code works or not, it should let you know when it's live!

(closing original issue, DOCUMENT_TEXT_DETECTION is now the default and seems to work well - but can be changed back to TEXT_DETECTION via config.txt if desired)

**Closed as completed by SethRobinson** 2021-08-03 00:17 UTC
